### PR TITLE
minor documentation updates

### PR DESCRIPTION
**Pull request by davidtedfordholt**
Not particularly important, but I wanted to fix a misspelling and got going. (_not_ an Oxford spelling thing!)

### CODE REVIEW

**Comment by mitchelloharawild** [comment]
\document

**Comment by davidtedfordholt** [comment]
That seems like beautiful shorthand, but I don't know for what. (I have problematically too many guesses)

**Comment by davidtedfordholt** [comment]
Ah, Github command

**Review by mitchelloharawild — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
